// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace taskslistDvpartners_backend.Models;

public partial class TasksHeader
{
    public int Id { get; set; }

    public int? Usercrea { get; set; }

    public DateTime Fecrea { get; set; }

    public int? Iduser { get; set; }

    public int? Estado { get; set; }

    public int? EstadoTarea { get; set; }

    public string Titutlo { get; set; }

    public string Observacion { get; set; }
}