// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace taskslistDvpartners_backend.Models;

public partial class taskslistDvpartnersContext : DbContext
{
    public taskslistDvpartnersContext(DbContextOptions<taskslistDvpartnersContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TasksBody> TasksBody { get; set; }

    public virtual DbSet<TasksHeader> TasksHeader { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TasksBody>(entity =>
        {
            entity.ToTable("tasksBody");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Color)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("color");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(350)
                .IsUnicode(false)
                .HasColumnName("descripcion");
            entity.Property(e => e.Eliminado).HasColumnName("eliminado");
            entity.Property(e => e.Estado).HasColumnName("estado");
            entity.Property(e => e.FechaFinTarea)
                .HasColumnType("datetime")
                .HasColumnName("fechaFinTarea");
            entity.Property(e => e.FechaInicioTarea)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("fechaInicioTarea");
            entity.Property(e => e.IdTasksHeader).HasColumnName("idTasksHeader");
            entity.Property(e => e.Observacion)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("observacion");
            entity.Property(e => e.Urlimagen)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("urlimagen");
        });

        modelBuilder.Entity<TasksHeader>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_tasksHeader2");

            entity.ToTable("tasksHeader");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Estado).HasColumnName("estado");
            entity.Property(e => e.EstadoTarea).HasColumnName("estadoTarea");
            entity.Property(e => e.FechaFinal)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("fechaFinal");
            entity.Property(e => e.Fecrea)
                .HasColumnType("datetime")
                .HasColumnName("fecrea");
            entity.Property(e => e.Iduser).HasColumnName("iduser");
            entity.Property(e => e.Observacion)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("observacion");
            entity.Property(e => e.Titutlo)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("titutlo");
            entity.Property(e => e.Usercrea).HasColumnName("usercrea");
        });

        modelBuilder.Entity<Users>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_users2");

            entity.ToTable("users");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Email)
                .HasMaxLength(120)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.Estado).HasColumnName("estado");
            entity.Property(e => e.Fecrea)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("fecrea");
            entity.Property(e => e.Nombres)
                .HasMaxLength(75)
                .IsUnicode(false)
                .HasColumnName("nombres");
            entity.Property(e => e.Password)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("password");
            entity.Property(e => e.Rol)
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("rol");
            entity.Property(e => e.Usercrea).HasColumnName("usercrea");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}