// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace taskslistDvpartners_backend.Models;

public partial class TasksBody
{
    public int Id { get; set; }

    public string Descripcion { get; set; }

    public string Urlimagen { get; set; }

    public int? IdTasksHeader { get; set; }

    public string Color { get; set; }

    public int? Estado { get; set; }

    public int? Eliminado { get; set; }

    public DateTime FechaInicioTarea { get; set; }

    public DateTime? FechaFinTarea { get; set; }

    public string Observacion { get; set; }
}