// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace taskslistDvpartners_backend.Models;

public partial class Users
{
    public int Id { get; set; }

    public string Nombres { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public int? Estado { get; set; }

    public string Rol { get; set; }

    public DateTime Fecrea { get; set; }

    public int? Usercrea { get; set; }
}